apiVersion: v1
kind: Service
metadata:
  name: webapp
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  type: NodePort
  selector:
    io.apisnoop.webapp: webapp
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
